version: '3'

services:
  server:
    build: ./server
    ports:
      - "2222:2222"
    networks:
      - inet
  client:
    build: ./client
    networks:
      - inet
    tty: true
    depends_on:
      - server

networks:
  inet:
    driver: bridge
